services:
  postgres-file-storage:
    image: postgres:16
    expose:
      - 5432
    env_file:
      - ./.env_docker
    volumes:
      - postgres-file-storage-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 5s
      retries: 3

  minio-file-storage:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./.env_docker
    volumes:
      - minio-file-storage-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis-file-storage:
    image: redis
    expose:
      - 6379
    volumes:
      - redis-file-storage-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  file-storage-api:
    image: file-storage-api
    build: .
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env_docker
    depends_on:
      postgres-file-storage:
        condition: service_healthy
      minio-file-storage:
        condition: service_healthy
      redis-file-storage:
        condition: service_healthy

  nginx-file-storage:
    image: nginx:1.27.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - file-storage-api

volumes:
  postgres-file-storage-data:
  minio-file-storage-data:
  redis-file-storage-data:
