"""tbl_file_rm_idx

Revision ID: 2f733c9fad03
Revises: 576f05a26298
Create Date: 2024-06-17 13:34:43.739860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f733c9fad03'
down_revision: Union[str, None] = '576f05a26298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_created_at', table_name='file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_file_created_at', 'file', ['created_at'], unique=False)
    # ### end Alembic commands ###
