"""tbl_file_add_uc

Revision ID: 576f05a26298
Revises: 58a4afc00313
Create Date: 2024-06-17 13:32:10.109682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576f05a26298'
down_revision: Union[str, None] = '58a4afc00313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_path_uc', 'file', ['user_id', 'path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_path_uc', 'file', type_='unique')
    # ### end Alembic commands ###
